name: cyberuday
description: "Cyber Uday citizen cyber safety and incident response app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^11.0.0
  google_generative_ai: ^0.4.5
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  file_picker: ^8.1.2
  crypto: ^3.0.6
  public_suffix: ^3.0.0
  google_mlkit_text_recognition: ^0.16.0
  google_mlkit_barcode_scanning: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/cyber_uday_mark.png
    - assets/public_suffix_list.dat
