import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateReportPdf(Map<String, dynamic> reportData) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('CYBER UDAY - Incident Report', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 24)),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Report ID: ${reportData['id'] ?? 'N/A'}'),
              pw.Text('Date: ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}'),
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Text('Incident Details:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
              pw.SizedBox(height: 10),
              pw.Bullet(text: 'Type: ${reportData['type'] ?? 'Cybercrime'}'),
              pw.Bullet(text: 'Description: ${reportData['description'] ?? ''}'),
              pw.Bullet(text: 'Victim Timeline: ${reportData['timeline'] ?? ''}'),
              pw.Bullet(text: 'Evidence: ${reportData['evidence'] ?? ''}'),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Text('This report was generated by the Cyber Uday Digital Bodyguard app.', style: pw.TextStyle(fontStyle: pw.FontStyle.italic)),
              pw.Text('Contact: support@cyberuday.com'),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
