// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qRHc_Bn6U5JrpBdRsq1dkztpRo_-DlA',
    appId: '1:1010516097616:web:d197062f8cb7a90ee8ef55',
    messagingSenderId: '1010516097616',
    projectId: 'cyber-uday-20',
    authDomain: 'cyber-uday-20.firebaseapp.com',
    storageBucket: 'cyber-uday-20.firebasestorage.app',
    measurementId: 'G-X4JTQ6R6EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsE4AmaOxpNQmp_YDfNd3iXYt0g0CbUr8',
    appId: '1:1010516097616:android:89722108574db1c6e8ef55',
    messagingSenderId: '1010516097616',
    projectId: 'cyber-uday-20',
    storageBucket: 'cyber-uday-20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzTPDyUonbI-re8SqAqVr5QTYgGeAl14',
    appId: '1:1010516097616:ios:0dddde85296ad86ee8ef55',
    messagingSenderId: '1010516097616',
    projectId: 'cyber-uday-20',
    storageBucket: 'cyber-uday-20.firebasestorage.app',
    iosBundleId: 'com.example.cyberuday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzTPDyUonbI-re8SqAqVr5QTYgGeAl14',
    appId: '1:1010516097616:ios:0dddde85296ad86ee8ef55',
    messagingSenderId: '1010516097616',
    projectId: 'cyber-uday-20',
    storageBucket: 'cyber-uday-20.firebasestorage.app',
    iosBundleId: 'com.example.cyberuday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qRHc_Bn6U5JrpBdRsq1dkztpRo_-DlA',
    appId: '1:1010516097616:web:49714ab220bbec1be8ef55',
    messagingSenderId: '1010516097616',
    projectId: 'cyber-uday-20',
    authDomain: 'cyber-uday-20.firebaseapp.com',
    storageBucket: 'cyber-uday-20.firebasestorage.app',
    measurementId: 'G-1PWVLDKLBX',
  );
}
